config/routes.rb
Rails.application.routes.draw do
  # put 'tasks/edit'
  # post 'tasks/create'
  # put 'lists/edit'
  # post 'lists/create'
  resources :lists do
    resources :tasks
  end
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
# frozen_string_literal: true

# List Model
class List < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: false
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
# frozen_string_literal: true

# Task Model
class Task < ApplicationRecord
  validates :title, :definition, presence: true
  belongs_to :list

  def self.to_csv(fields = column_names)
    CSV.generate do |csv|
      csv << fields
      all.each do |result|
        csv << result.attributes.values_at(*fields)
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, :last_name, :email, presence: true
  validates :password, presence: true, on: :create
  # validates :current_password, presence: true, on: :update
  validates :description, presence: false
  has_one_attached :photo
  has_many :lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[first_name last_name description photo]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @list = List.new
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

# Lists Controller
class ListsController < ApplicationController
  before_action :find_list, only: %i[show edit update destroy]
  before_action :authenticate_user!
  def index; end

  def new
    @list = List.new
    # @task = Task.new
  end

  def edit; end

  def create
    @list = current_user.lists.new(list_params)
    # raise @list.to_yaml
    @list.created_date = Time.now
    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path, notice: 'List was successfully created' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { redirect_to new_list_path, alert: 'List was not valid, try again' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_path, notice: 'List was successfully updated' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { redirect_to edit_list_path(@list), alert: 'List was not valid, try again' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.csv { send_data @list.tasks.to_csv(%w[title definition state]) }
      format.pdf { render template: 'tasks/tasklist', pdf: 'Tasks', page_size: 'Letter' }
      # format.csv { send_data @list.tasks.to_csv }
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_list
    # @list = List.find(params[:format] || params[:id])
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(%i[title description created_date])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# Tasks Controller
class TasksController < ApplicationController
  before_action :find_list, only: %i[index new show create edit update destroy]
  def index; end

  def new
    @task = Task.new
  end

  def create
    @task = @list.tasks.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @list, notice: 'Task was successfully created' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { redirect_to list_path(@list), alert: 'Task was not valid, try again' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @task = @list.tasks.find(params[:id])
  end

  def update
    @task = @list.tasks.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @list, notice: 'Task was successfully updated' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { redirect_to list_path(@list), alert: 'Task was not valid, try again' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def destroy
    @task = @list.tasks.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@list), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
    # redirect_to @list
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def task_params
    params.require(:task).permit(%i[title definition state added_date])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
    <div class="row">
        <!-- <h1>To Do</h1> -->
    </div>
    <% if !user_signed_in? %>
        <!-- Login -->
        <!-- TODO: default user image -->
        <div class="container">
            <!-- <%= image_tag "icon3.png" %> -->
            <div class="card text-center">
                <!-- <%= image_tag "icon2.jpg", class: "card-img-top", alt: "ToDoIcon" %> -->
                <!-- <img class="card-img-top" src="" alt=""> -->
                <div class="card-body">
                    <%= render new_user_session_path %>
                    <%= render "devise/shared/links" %>
                    <%= link_to 'Create an account free', new_user_registration_path %>
                    <!-- <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#contentId" aria-expanded="false"
                            aria-controls="contentId">
                        Show
                    </button>
                    <div class="collapse" id="contentId">
                        <%= render new_user_registration_path %>
                    </div> -->
                
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless notice.nil? %>
      <div class="alert alert-success" role="alert">
          <small class="notice"><%= notice %></small>
      </div>
    <% end %>
    <% unless alert.nil? %>
      <div class="alert alert-danger" role="alert">
          <small class="alert"><%= alert %></small>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <div class="main-col">
        <div class="card">
          <!-- TODO: default user image -->
          <% if current_user.photo.attached? %>
              <image src="<%= (url_for(current_user.photo)) %>" class="card-img-top user-img"/>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= current_user.first_name + ' ' + current_user.last_name %></h5>
            <span><small><%= current_user.email %></small></span>
            <hr>
            <p class="card-text">
              <%= current_user.description %>
            </p>
          </div>
          <div class="btn-group" role="group">
            <%= link_to destroy_user_session_path, class: 'btn btn-danger font_button',
                title: 'Sign out', method: :delete do %>
                <%= fa_icon "sign-out" %>
            <% end %>
            
            <%= link_to edit_user_registration_path, class: 'btn btn-info font_button',
                title: 'Edit user' do %>
                <%= fa_icon "edit" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="lists">
        <%= render 'lists/partials/index' %>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  <footer>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <p>
              BrightCoders - 2019
          </p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/lists/edit.html.erb
<%= render 'lists/partials/edit' %>

app/views/lists/index.html.erb
<p>index</p>

app/views/lists/new.html.erb
<%= render 'lists/partials/new' %>

app/views/lists/partials/_edit.html.erb
<div class="container-fluid edit-form">
    <div class="row">
        <div class="col">
            <h2>Edit list</h2>
        </div>
    </div>
    <div class="container">
        <%= form_for @list, action: :update do |f| %>
        <div class="form-group row">
            <%= f.label :title, class: 'col-sm-1 col-form-label' %>
            <div class="col-sm-4">
                <%= f.text_field :title, class: 'form-control form-control-sm' %>
            </div>
        </div>

        <div class="form-group row">
            <%= f.label :description, class: 'col-sm-1 col-form-label' %>
            <div class="col-sm-4">
                <%= f.text_area :description, class: 'form-control form-control-sm' %>
            </div>
        </div>

        <div class="row">
            <div class="col-5">
                <%= f.submit "Update", class: 'btn btn-success btn-block', title: 'Save changes' %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/lists/partials/_index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <%= link_to new_list_path, title: 'Create a new list', class: 'btn btn-outline-success btn-block' do %>
                <%= fa_icon "plus" %>
                <span>Add a new list</span>
            <% end %>
            <ul class="list-group list-group-flush">
            <% if current_user.lists.length > 0 %>
                <% current_user.lists.each do |list| %>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col">
                                <h5><%= list.title %></h5>
                            </div>
                            <div class="btn-group col" role="group">
                                <%= link_to list, class: 'btn btn-info',
                                    title: 'Show tasks', id: "show-list#{list.id}" do %>
                                    <%= fa_icon "list" %>
                                    <span class="badge"><%= list.tasks.length %></span>
                                <% end %>
                                <%= link_to edit_list_path(list), class: 'btn btn-info',
                                    title: 'Edit list' do %>
                                    <%= fa_icon "edit" %>
                                <% end %>
                                <%= link_to list, method: :delete, data: { confirm: 'Are you sure?' },
                                    title: "Delete list", id: "del-list#{list.id}", class: 'btn btn-danger' do %>
                                    <%= fa_icon "trash" %>
                                <% end %>
                            </div>
                        </div>
                        <small><em><%= list.description %></em></small>
                    </li>
                <% end %>
            <% else %>
                <h2>Nothing to do</h2>
            <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/lists/partials/_new.html.erb
<div class="container-fluid new-element">
    <div class="row">
        <div class="col">
            <h2>New list</h2>
        </div>
    </div>
    <div class="container">
        <%= form_for @list, action: :create do |f| %>
            <div class="form-group row">
                <%= f.label :title, class: 'col-sm-1 col-form-label' %>
                <div class="col-sm-4">
                    <%= f.text_field :title, class: 'form-control form-control-sm', required: true %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label 'description', class: 'col-sm-1 col-form-label' %>
                <div class="col-sm-4">
                    <%= f.text_area :description, class: 'form-control form-control-sm', placeholder: 'Type something...' %>
                    <small class="form-text text-muted">Optional</small>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-5">
                    <%= f.submit "Add list", class: 'btn btn-success btn-lg btn-block' %>
                </div>
            </div>
        <% end %> 
    </div> 
</div>

app/views/lists/show.html.erb
<div class="container-fluid tasks">
    <div class="row">
        <div class="col">
            <h2><%= @list.title %></h2>
        </div>
        <div class="col">
            <div class="btn-group" role="group" aria-label="Basic example">
                <%= link_to new_list_task_path(@list), class: 'btn btn-outline-success',
                    title: 'Add a new task' do %>
                    <%= fa_icon "plus" %>
                    <span>Add a new task</span>
                <% end %>
                <%= link_to list_path(@list, format: 'csv'), class: 'btn btn-info font_button_list',
                    title: 'Export list to CSV' do %>
                    <%= fa_icon "file" %>
                    <span>CSV</span>
                <% end %>
                <%= link_to list_path(@list, format: 'pdf'), class: 'btn btn-info font_button_list',
                    title: 'Export list to PDF' do %>
                    <%= fa_icon "file" %>
                    <span>PDF</span>
                <% end %>
            </div>            
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>
                <%= @list.description %>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <ul class="list-group list-group-flush">
                <% if @list.tasks.length > 0 %>
                    <% @list.tasks.each do |task| %>
                        <% if task.state %>
                            <li class="list-group-item list-group-item-success">
                                <div class="row">
                                    <div class="col">
                                        <h5><%= fa_icon "check", title: 'Completed' %><%= task.title %></h5>
                                    </div>
                                    <div class="btn-group col-sm-2" role="group">
                                        <%= link_to edit_list_task_path(@list, task), class: 'btn btn-info font_button_list',
                                            title: 'Edit task' do %>
                                            <%= fa_icon "edit" %>
                                        <% end %>                            
                                        <%= link_to [@list, task], method: :delete, data: { confirm: 'Are you sure?' },
                                            title: 'Delete task', class: 'btn btn-danger font_button_list' do %>
                                            <%= fa_icon "trash" %>
                                        <% end %>
                                    </div>
                                </div>
                                <p><%= task.definition %></p>
                            </li>
                        <% else %>
                            <li class="list-group-item list-group-item-warning">
                                <div class="row" title="Incomplete">
                                    <div class="col">
                                        <h5><%= fa_icon "times", title: 'Incomplete' %><%= task.title %></h5>
                                    </div>
                                    <div class="btn-group col-sm-2" role="group">
                                        <%= link_to edit_list_task_path(@list, task), class: 'btn btn-info font_button_list',
                                            title: 'Edit task' do %>
                                            <%= fa_icon "edit" %>
                                        <% end %>                            
                                        <%= link_to [@list, task], method: :delete, data: { confirm: 'Are you sure?' },
                                            title: 'Delete task', id: "del-task#{task.id}", class: 'btn btn-danger font_button_list' do %>
                                            <%= fa_icon "trash" %>
                                        <% end %>
                                    </div>
                                </div>
                                <p><%= task.definition %></p>
                            </li>
                        <% end %>
                    <% end %>    
                <% else %>
                    <p><h1>None tasks</h1></p>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/partials/_new_user.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/tasks/edit.html.erb
<%= render 'tasks/partials/edit' %>

app/views/tasks/new.html.erb
<%= render 'tasks/partials/new' %>

app/views/tasks/partials/_edit.html.erb
<div class="container-fluid edit-form">
    <div class="row">
        <div class="col">
            <h2><%= @list.title %> | Edit task</h2>
        </div>
    </div>
    <div class="container">
        <%= form_for [@list,@task], action: :update do |f| %>
            <div class="form-group row">
                <%= f.label :title, class: 'col-sm-1 col-form-label' %>
                <div class="col-sm-4">
                    <%= f.text_field :title, class: 'form-control form-control-sm' %>
                </div>
            </div>

            <div class="form-group row">
                <%= f.label :definition, class: 'col-sm-1 col-form-label' %>
                <div class="col-sm-4">
                    <%= f.text_area :definition, class: 'form-control form-control-sm' %>
                </div>
            </div>

            <div class="form-group row">
                <%= f.label 'Done?', class: 'col-sm-1 col-form-label' %>
                <div class="col-sm-1">
                    <%= f.check_box :state, class: 'form-control form-control-sm' %>
                </div>
            </div>
            
            <div class="row">
                <div class="col-5">
                    <%= f.submit "Update", class: 'btn btn-success btn-block', title: 'Save changes' %>
                </div>
            </div>
        <% end %>
    </div>
    
</div>

app/views/tasks/partials/_new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h2>New task for <%= @list.title %></h2>
        </div>
    </div>
    <div class="container">
        <%= form_for @task, url: list_tasks_path do |f| %>
            <div class="form-group row">
                <%= f.label :title, class: 'col-sm-2 col-form-label' %>
                <div class="col-sm-7">
                    <%= f.text_field :title, class: 'form-control form-control-sm', required: true %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label :definition, class: 'col-sm-2 col-form-label' %>
                <div class="col-sm-7">
                    <%= f.text_area :definition, class: 'form-control form-control-sm', placeholder: 'Type something...' %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label 'Done?', class: 'col-sm-2 col-form-label' %>
                <div class="col-sm-1">
                    <%= f.check_box :state, class: 'form-control form-control-sm' %>
                </div>
            </div>
            <div class="row">
                <div class="col-9">
                    <%= f.submit "Add task", class: 'btn btn-success btn-block', title: 'Save changes' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/tasklist.pdf.erb
<html>
    <head>
        <title>todo list</title>
        <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
    </head>
    <body>
        <div>
            <h1><%= @list.title %></h1>
            <p><%= @list.description %></p>
            <table>
                <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Definition</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                    <% @list.tasks.each do |task| %>
                        <tr>
                            <td scope="row"><%= task.title %></td>
                            <td><%= task.definition %></td>
                            <% if task.state%>
                                <td>Completed</td>
                            <% else %>
                                <td>Incomplete</td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </body>
    <footer>
    </footer>
</html>

app/views/users/_sign_in.html.erb
<%= render 'devise/sessions/new' %>

app/views/users/_sign_up.html.erb
<%= render 'devise/registrations/new' %>